version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cake-shop-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=production_password
      - DB_NAME=cake_shop_prod
    volumes:
      - ./logs:/app/logs
    networks:
      - cake-shop-network

  db:
    image: mysql:8.0
    container_name: cake-shop-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=production_password
      - MYSQL_DATABASE=cake_shop_prod
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - cake-shop-network

  nginx:
    image: nginx:alpine
    container_name: cake-shop-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - cake-shop-network

networks:
  cake-shop-network:
    driver: bridge

volumes:
  db_data:
    driver: local 